# Generated by scripts/gen-packaging.mjs in Env-Kit/envkit — do not edit by hand.
cask "envkit" do
  version "0.33.0-beta.29"
  sha256 "81310a46cd2de58e30ff6fbc6f54147a644a31e86710b52c057634c6d5bd5e57"

  url "https://github.com/Env-Kit/envkit-releases/releases/download/v#{version}/EnvKit-#{version}-arm64.dmg"
  name "EnvKit"
  desc "Local web development stack with trusted .test HTTPS"
  homepage "https://envkit.net/"

  livecheck do
    url :url
    regex(/^v?(\d+(?:\.\d+)+(?:-[a-z]+(?:\.\d+)?)?)$/i)
    strategy :github_latest
  end

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :monterey

  app "EnvKit.app"

  postflight_steps do
    write_file "Library/Application Support/envkit/install-source.txt", "brew\n", base: :home
  end

  uninstall quit: "com.envkit.app"

  zap trash: [
    "~/Library/Application Support/EnvKit",
    "~/Library/Caches/com.envkit.app",
    "~/Library/Caches/com.envkit.app.ShipIt",
    "~/Library/HTTPStorages/com.envkit.app",
    "~/Library/Logs/EnvKit",
    "~/Library/Preferences/com.envkit.app.plist",
    "~/Library/Saved Application State/com.envkit.app.savedState",
  ]

  caveats <<~EOS
    EnvKit is code-signed but not yet notarized by Apple, so Gatekeeper may
    block the first launch. Run

      xattr -dr com.apple.quarantine /Applications/EnvKit.app

    or, after the first blocked launch, allow it in System Settings →
    Privacy & Security → Open Anyway.
  EOS
end
